### ISSUE TITLE
TuxOn problems

### ISSUE THREAD

**Issue by DaveBenham** [kockie69/RPJ#59]
Windows and Macintosh:
 * Zoom In and Zoom Out not doing anything
 * Limited song length
   * If song long enough, then impossible to play entire song
   * VCV sample rate affects how much can be played, but sound quality remains same. For example, I have a ~3:50 mp3 recorded at 48k that can be played in its entirety if VCV sample rate is at 48k. If at 96k then only ~2:50 plays, though entire songs is graphically displayed - it just simply stops playing before reaching end. VCV at 192k only plays ~1:25.

Macintosh only
  * VCV Rack crashes after playing a song when I try to load a new patch. Also, VCV does not shut down properly if I try to close after playing a song
  * Eject does not work, neither does selecting a new song via the context menu

**Comment by kockie69** [comment]
Hi Dave, not sure if you are handling the zoom function in the right way. You need to change the start and end first (or one of the two). Than you can drill. Otherwise it doesn't know to drill within which interval.

I will look into the other issues.

**Comment by DaveBenham** [comment]
Well that makes sense. Sounds like good info for the documentation ;-)

The zoom in behavior surprises me. Currently the start and end positions change each time you press zoom in. By that I mean the points in the song that they represent change upon each zoom in - call that the play zone.

I would expect the play zone to remain constant, meaning that after the zoom in operation, the start and end lines would be at the outer edges of the zoomed in area.

**Comment by kockie69** [comment]
I fully agree with you, but that wasn't straight forward to implement at
the time. If I know people want it I will implement it. Happy to pick up.

the issue 'If song long enough, then impossible to play entire song' I can reproduce. In general something seems wrong with different speeds. Looking into it.

**Comment by kockie69** [comment]
Hi Dave, you said

_I would expect the play zone to remain constant, meaning that after the zoom in operation, the start and end lines would be at the outer edges of the zoomed in area._

And I agreed. But........
Whilst implementing I ran into the issue that the begin and end knobs don't reset to the full left and full right respectively when zooming in. That means (for example for begin) according to the display you can go the right but your knob can't anymore.

I don't have a solution yet, happy to hear your thoughts.

**Comment by DaveBenham** [comment]
It took me a few moments to understand your point, but I got there. I know there have been a few modules that move the knobs, but not many.

It is a little awkward, because the begin/end markers represent two different values - the position on the screen, and the position within the mp3.

I'm not sure if this is the correct term, but I'm thinking it would make sense to use a "rotary encoder" knob, where it can spin "infinitely" in either direction. The amount you spin the knob dictates how far it moves. You wouldn't have to reset the knobs with that type of control.

**Comment by kockie69** [comment]
Hi Dave, I was also thinking about the rotary knob, but I couldn't find one
on my own rack. But I guess they will exist. I think that is the best
solution so I will create one tomorrow.

Ok, checked and it has been done before in vcv. 

 Thanks.

**Comment by kockie69** [comment]
Dave, I have fixed the issues, except for the specific Mac ones.
Are you happy/able to test the fixes for me? You can download a version from here.

https://github.com/kockie69/RPJ/actions/runs/2530109697

**Comment by DaveBenham** [comment]
Sure. I'll take a look either today or tomorrow

**Comment by DaveBenham** [comment]
Yep - the Mac issues are still there. But the song length and zoom are now working perfectly on both Mac and PC. Thanks.
